# Generated by Django 5.0.3 on 2024-03-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection',
            field=models.BooleanField(default=False),
        ),
    ]
