# Generated by Django 5.0.3 on 2024-04-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_db', '0003_connection_username_alter_connection_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='comment',
            new_name='description',
        ),
    ]
