# Generated by Django 5.0.3 on 2024-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
