# Generated by Django 5.0.3 on 2024-04-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_token_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='username',
            new_name='name',
        ),
    ]
