# Generated by Django 5.0.3 on 2024-04-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='description',
        ),
    ]
