# Generated by Django 5.0.3 on 2024-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(blank=True, null=True)),
                ('date_delete', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_type', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('EXCEL', 'EXCEL'), ('PDF', 'PDF'), ('Other', 'Other')], default='Other', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Community', 'Community'), ('My_files', 'My_files'), ('Best_practices', 'Best Practices')], default='Community', max_length=25)),
            ],
        ),
    ]
