# Generated by Django 5.0.3 on 2024-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
