# Generated by Django 5.0.3 on 2024-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_access_open', models.DateTimeField(auto_now_add=True)),
                ('date_access_close', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('Reader', 'Reader'), ('Owner', 'Owner'), ('Commentator', 'Commentator'), ('Editor', 'Editor')], default='Reader', max_length=25)),
            ],
        ),
    ]
